### ISSUE TITLE
An article talking about gov applications for election 62

### ISSUE THREAD

**Issue by p16i** [codeforthailand/awesome-election-62#6]
Hi,

I've just written [an article][link] on Medium, talking about applications provided by our government for the election. 

Do you think it's appropriate to include this article here? Is there anything I should discuss more in the article?

[link]: https://medium.com/@p16i/มองระบบที่ทางภาครัฐฯ-พัฒนาขึ้น-สำหรับการเลือกตั้งครั้งที่-28-24-มี-ค-2562-20d8d4621062

**Comment by unnawut** [comment]
Yeah definitely can go on the list. I think the length and depth of content is just right for an introduction to various tools.

One small suggestion though, I don't remember what those tools look like right now, it's been a few months. Having key screenshots of those tools would help paint the picture, imho.

Feel free to add it to the README right away. Otherwise I can do this evening after work.

**Comment by p16i** [comment]
Thanks for pointing out about screenshots. Actually there were images in the article but somehow they weren't included when I exported the article from my editor to Medium. 

Now they're back.
